// Code generated by MockGen. DO NOT EDIT.
// Source: svc.go
//
// Generated by this command:
//
//	mockgen -source svc.go -destination=../../../../../mocks/assets_mocks/svc.go -package=assets_mocks
//
// Package assets_mocks is a generated GoMock package.
package assets_mocks

import (
	context "context"
	reflect "reflect"

	assets "github.com/base-media-cloud/pd-iconik-io-rd/internal/core/domain/iconik/assets/assets"
	gomock "go.uber.org/mock/gomock"
)

// MockServicer is a mock of Servicer interface.
type MockServicer struct {
	ctrl     *gomock.Controller
	recorder *MockServicerMockRecorder
}

// MockServicerMockRecorder is the mock recorder for MockServicer.
type MockServicerMockRecorder struct {
	mock *MockServicer
}

// NewMockServicer creates a new mock instance.
func NewMockServicer(ctrl *gomock.Controller) *MockServicer {
	mock := &MockServicer{ctrl: ctrl}
	mock.recorder = &MockServicerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServicer) EXPECT() *MockServicerMockRecorder {
	return m.recorder
}

// GetAsset mocks base method.
func (m *MockServicer) GetAsset(ctx context.Context, path, assetID string) (assets.DTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAsset", ctx, path, assetID)
	ret0, _ := ret[0].(assets.DTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAsset indicates an expected call of GetAsset.
func (mr *MockServicerMockRecorder) GetAsset(ctx, path, assetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAsset", reflect.TypeOf((*MockServicer)(nil).GetAsset), ctx, path, assetID)
}

// UpdateAsset mocks base method.
func (m *MockServicer) UpdateAsset(ctx context.Context, path, assetID string, payload []byte) (assets.DTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAsset", ctx, path, assetID, payload)
	ret0, _ := ret[0].(assets.DTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateAsset indicates an expected call of UpdateAsset.
func (mr *MockServicerMockRecorder) UpdateAsset(ctx, path, assetID, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAsset", reflect.TypeOf((*MockServicer)(nil).UpdateAsset), ctx, path, assetID, payload)
}

// ValidateAsset mocks base method.
func (m *MockServicer) ValidateAsset(ctx context.Context, assetID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateAsset", ctx, assetID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateAsset indicates an expected call of ValidateAsset.
func (mr *MockServicerMockRecorder) ValidateAsset(ctx, assetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateAsset", reflect.TypeOf((*MockServicer)(nil).ValidateAsset), ctx, assetID)
}
